### ISSUE TITLE
how to add proxy?

### ISSUE THREAD

**Issue by PassiveIncomeMachine** [zhangjh/gemini_sdk#2]
how to add proxy? thx

**Comment by zhangjh** [comment]
It's another topic, you can look at [the docs about v2ray](https://www.v2fly.org/) here.
You can also use this [shell script](https://github.com/233boy/v2ray) to set up v2ray quickly and conveniently.
Once you set up your v2ray service, you can set the proxy enviroment variable by using the command like this:
`export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;export ALL_PROXY=socks5://127.0.0.1:1080;`

**Comment by zhangjh** [comment]
I have already support adding local proxy in this sdk project.
Look at the code: `me.zhangjh.gemini.util.HttpClientUtil`
![image](https://github.com/zhangjh/gemini_sdk/assets/3371714/9f1c3f84-b174-413a-963e-928a7f541bf3)
